from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ScaffoldFile:
    path: str | Path
    content: str | bytes
    kind: str = "file"
    executable: bool = False
    encoding: str = "utf-8"


@dataclass(frozen=True)
class ScaffoldPlan:
    name: str
    root: str | Path
    files: Sequence[ScaffoldFile] = ()
    directories: Sequence[str | Path] = ()
    commands: Mapping[str, Any] = field(default_factory=dict)
    env: Mapping[str, Any] = field(default_factory=dict)
    client: Mapping[str, Any] = field(default_factory=dict)
    smoke_checks: Sequence[Mapping[str, Any]] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class GeneratedArtifact:
    name: str
    path: str | Path
    kind: str = "file"
    description: str = ""


@dataclass(frozen=True)
class GeneratedCommand:
    name: str
    command: Any
    description: str = ""
    kind: str = "command"


@dataclass(frozen=True)
class GeneratedClient:
    name: str
    url: str
    headers: Mapping[str, str] = field(default_factory=dict)
    config: str | Path | None = None
    description: str = ""


@dataclass(frozen=True)
class GeneratedEnv:
    name: str
    value: str
    description: str = ""


@dataclass(frozen=True)
class GeneratedLog:
    name: str
    path: str | Path
    kind: str = "jsonl"
    description: str = ""


@dataclass(frozen=True)
class GeneratedSession:
    name: str
    root: str | Path
    generated_by: str = ""
    artifacts: Sequence[GeneratedArtifact] = ()
    commands: Sequence[GeneratedCommand] = ()
    clients: Sequence[GeneratedClient] = ()
    env: Sequence[GeneratedEnv] = ()
    logs: Sequence[GeneratedLog] = ()
    next_steps: Sequence[str] = ()
    scaffolds: Sequence[Mapping[str, Any]] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)


def json_scaffold_file(
    path: str | Path,
    value: Any,
    *,
    kind: str = "json",
    executable: bool = False,
) -> ScaffoldFile:
    return ScaffoldFile(
        path=path,
        content=json.dumps(value, indent=2, sort_keys=True) + "\n",
        kind=kind,
        executable=executable,
    )


def session_result(session: GeneratedSession, *, ok: bool = True) -> dict[str, Any]:
    artifacts = [_artifact_result(artifact) for artifact in session.artifacts]
    commands = [_command_result(command) for command in session.commands]
    clients = [_client_result(client) for client in session.clients]
    env = [_env_result(item) for item in session.env]
    logs = [_log_result(log) for log in session.logs]
    return {
        "ok": ok,
        "name": session.name,
        "generated_by": session.generated_by,
        "root": str(session.root),
        "artifacts": artifacts,
        "file_map": {artifact["name"]: artifact["path"] for artifact in artifacts},
        "commands": commands,
        "command_map": {command["name"]: command["command"] for command in commands},
        "clients": clients,
        "primary_client": clients[0] if clients else None,
        "env": env,
        "env_map": {item["name"]: item["value"] for item in env},
        "logs": logs,
        "log_map": {log["name"]: log["path"] for log in logs},
        "next_steps": list(session.next_steps),
        "scaffolds": [dict(scaffold) for scaffold in session.scaffolds],
        "metadata": dict(session.metadata),
    }


def format_session_report(result: GeneratedSession | Mapping[str, Any]) -> str:
    session = session_result(result) if isinstance(result, GeneratedSession) else dict(result)
    lines = [f"# {session.get('name', 'snulbug session')}", ""]
    generated_by = session.get("generated_by")
    if generated_by:
        lines.extend([f"Generated by: `{generated_by}`", ""])
    root = session.get("root")
    if root:
        lines.extend([f"Root: `{root}`", ""])

    client = session.get("primary_client")
    if isinstance(client, Mapping):
        lines.extend(["## Client", "", f"- URL: `{client.get('url')}`"])
        config = client.get("config")
        if config:
            lines.append(f"- Config: `{config}`")

    commands = session.get("commands")
    if isinstance(commands, Sequence) and not isinstance(commands, str | bytes | bytearray) and commands:
        lines.extend(["", "## Commands", ""])
        for command in commands:
            if isinstance(command, Mapping):
                lines.append(f"- `{command.get('name')}`: `{command.get('command')}`")

    logs = session.get("logs")
    if isinstance(logs, Sequence) and not isinstance(logs, str | bytes | bytearray) and logs:
        lines.extend(["", "## Logs", ""])
        for log in logs:
            if isinstance(log, Mapping):
                lines.append(f"- `{log.get('name')}`: `{log.get('path')}`")

    next_steps = session.get("next_steps")
    if isinstance(next_steps, Sequence) and not isinstance(next_steps, str | bytes | bytearray) and next_steps:
        lines.extend(["", "## Next Steps", ""])
        lines.extend(f"- `{step}`" for step in next_steps)
    return "\n".join(lines).rstrip() + "\n"


def write_scaffold(plan: ScaffoldPlan, *, force: bool = False) -> dict[str, Any]:
    root = Path(plan.root)
    directories = [_resolve_scaffold_path(root, directory) for directory in plan.directories]
    files = [_materialize_file(root, file) for file in plan.files]

    for directory in directories:
        if directory.exists() and not directory.is_dir():
            raise FileExistsError(f"{plan.name} output already exists and is not a directory: {directory}")
    for file, path in files:
        if path.exists() and not force:
            raise FileExistsError(f"{plan.name} output already exists: {path}")

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
    for file, path in files:
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(file.content, bytes):
            path.write_bytes(file.content)
        else:
            path.write_text(file.content, encoding=file.encoding)
        if file.executable:
            path.chmod(path.stat().st_mode | 0o111)

    return scaffold_result(plan, files=files, directories=directories)


def scaffold_result(
    plan: ScaffoldPlan,
    *,
    files: Sequence[tuple[ScaffoldFile, Path]] | None = None,
    directories: Sequence[Path] | None = None,
) -> dict[str, Any]:
    root = Path(plan.root)
    materialized_files = list(files) if files is not None else [_materialize_file(root, file) for file in plan.files]
    materialized_dirs = (
        list(directories)
        if directories is not None
        else [_resolve_scaffold_path(root, directory) for directory in plan.directories]
    )
    return {
        "ok": True,
        "name": plan.name,
        "root": str(root),
        "files": [
            {
                "path": str(path),
                "kind": file.kind,
                "executable": file.executable,
            }
            for file, path in materialized_files
        ],
        "written_files": [str(path) for _file, path in materialized_files],
        "directories": [str(path) for path in materialized_dirs],
        "commands": dict(plan.commands),
        "env": dict(plan.env),
        "client": dict(plan.client),
        "smoke_checks": [dict(check) for check in plan.smoke_checks],
        "metadata": dict(plan.metadata),
    }


def format_scaffold_report(result: Mapping[str, Any]) -> str:
    lines = [f"# {result.get('name', 'snulbug scaffold')}", ""]
    root = result.get("root")
    if root:
        lines.extend([f"Root: `{root}`", ""])
    files = result.get("written_files")
    if isinstance(files, Sequence) and not isinstance(files, str | bytes | bytearray):
        lines.extend(["## Files", ""])
        lines.extend(f"- `{file}`" for file in files)
    commands = result.get("commands")
    if isinstance(commands, Mapping) and commands:
        lines.extend(["", "## Commands", ""])
        lines.extend(f"- `{key}`: `{value}`" for key, value in commands.items())
    return "\n".join(lines).rstrip() + "\n"


def _materialize_file(root: Path, file: ScaffoldFile) -> tuple[ScaffoldFile, Path]:
    return file, _resolve_scaffold_path(root, file.path)


def _resolve_scaffold_path(root: Path, path: str | Path) -> Path:
    value = Path(path)
    return value if value.is_absolute() else root / value


def _artifact_result(artifact: GeneratedArtifact) -> dict[str, Any]:
    return {
        "name": artifact.name,
        "path": str(artifact.path),
        "kind": artifact.kind,
        "description": artifact.description,
    }


def _command_result(command: GeneratedCommand) -> dict[str, Any]:
    return {
        "name": command.name,
        "command": command.command,
        "kind": command.kind,
        "description": command.description,
    }


def _client_result(client: GeneratedClient) -> dict[str, Any]:
    result: dict[str, Any] = {
        "name": client.name,
        "url": client.url,
        "headers": dict(client.headers),
        "description": client.description,
    }
    if client.config is not None:
        result["config"] = str(client.config)
    return result


def _env_result(env: GeneratedEnv) -> dict[str, Any]:
    return {
        "name": env.name,
        "value": env.value,
        "description": env.description,
    }


def _log_result(log: GeneratedLog) -> dict[str, Any]:
    return {
        "name": log.name,
        "path": str(log.path),
        "kind": log.kind,
        "description": log.description,
    }
